### ISSUE TITLE
UI commit functions failed (connect ECONNREFUSED 127.0.0.1:8080)

### ISSUE THREAD

**Issue by Achonger09** [kubeless/kubeless-ui#93]
![image](https://user-images.githubusercontent.com/35490338/90330270-fd614c00-dfdd-11ea-82ff-b6a083315a57.png)
minikube (signal node)
```
sudo minikube start --image-mirror-country cn     --iso-url=https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.9.0.iso     --registry-mirror=https://mirror.aliyuncs.com --vm-driver=none --insecure-registry=[192.168.31.211:5000]

sudo kubectl proxy --port=8001 --accept-hosts='^.*' --address='192.168.31.211'
```
docker version
```
# docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
kubeless version
```
# kubeless version
Kubeless version: v1.0.7-dirty
```
create,call function success by cli
```
# kubeless function call hello --data 'Hello world!'
Hello world!
```
but create function in UI failed
and server error info
```
# yarn run dev
yarn run v1.22.4
$ better-npm-run dev
running better-npm-run in /k8s/kubeless/kubeless-ui
Executing script: dev

to be executed: nodemon bin/server --ignore dist --ignore coverage --ignore tests --ignore src
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node bin/server index.js`
  app:config:project Creating default configuration. +0ms
  app:config:project Looking for environment overrides for NODE_ENV "development". +3ms
  app:config:project Found overrides, applying to default configuration. +1ms
  app:config:webpack Creating configuration. +808ms
  app:config:webpack Enabling plugins for live development (HMR, NoEmitOnErrors). +2ms
  app:server Enabling webpack dev and HMR middleware +134ms
  app:bin:server
  app:bin:server
  app:bin:server  💻  Server is now running at localhost:3000 +43ms
(node:4443) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (/k8s/kubeless/kubeless-ui/node_modules/babel-loader/node_modules/loader-utils/index.js:78:3)
    at Object.module.exports (/k8s/kubeless/kubeless-ui/node_modules/babel-loader/lib/index.js:104:35)
    at LOADER_EXECUTION (/k8s/kubeless/kubeless-ui/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/k8s/kubeless/kubeless-ui/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/k8s/kubeless/kubeless-ui/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/k8s/kubeless/kubeless-ui/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/k8s/kubeless/kubeless-ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
    at /k8s/kubeless/kubeless-ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
    at /k8s/kubeless/kubeless-ui/node_modules/graceful-fs/graceful-fs.js:115:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
webpack built b401a52cb111a9aeacc2 in 9882ms
Hash: b401a52cb111a9aeacc2
Version: webpack 2.4.1
Time: 9882ms
                                                                            Asset       Size  Chunks                    Chunk Names
/k8s/kubeless/kubeless-ui/node_modules/font-awesome/fonts/fontawesome-webfont.eot     166 kB          [emitted]
                                             ba89e316e1e812fc4e91923f94d76895.png    24.5 kB          [emitted]
                                                      app.b401a52cb111a9aeacc2.js    4.73 MB       0  [emitted]  [big]  app
                                                   vendor.b401a52cb111a9aeacc2.js     445 kB       1  [emitted]  [big]  vendor
                                                  app.b401a52cb111a9aeacc2.js.map    5.53 MB       0  [emitted]         app
                                               vendor.b401a52cb111a9aeacc2.js.map     493 kB       1  [emitted]         vendor
                                                                      favicon.ico    34.5 kB          [emitted]
                                                                       index.html  977 bytes          [emitted]
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks  Chunk Names
    index.html  571 kB       0
webpack: Compiled successfully.
  app:server Error: request to http://localhost:8080/api/v1/namespaces/kubeless/configmaps/kubeless-config failed, reason: connect ECONNREFUSED 127.0.0.1:8080 +17s
  app:server Error: request to http://localhost:8080/api/v1/pods failed, reason: connect ECONNREFUSED 127.0.0.1:8080 +28ms
  app:server Error: request to http://localhost:8080/apis/kubeless.io/v1beta1/functions failed, reason: connect ECONNREFUSED 127.0.0.1:8080 +1ms
  app:server Error: request to http://localhost:8080/api/v1/namespaces/kubeless/configmaps/kubeless-config failed, reason: connect ECONNREFUSED 127.0.0.1:8080 +57ms
  app:server Error: request to http://localhost:8080/api/v1/namespaces/kubeless/configmaps/kubeless-config failed, reason: connect ECONNREFUSED 127.0.0.1:8080 +2s
  app:server Error: request to http://localhost:8080/api/v1/namespaces/kubeless/configmaps/kubeless-config failed, reason: connect ECONNREFUSED 127.0.0.1:8080 +1ms
  app:server Error: request to http://localhost:8080/api/v1/namespaces/kubeless/configmaps/kubeless-config failed, reason: connect ECONNREFUSED 127.0.0.1:8080 +18s
  app:server Error: request to http://localhost:8080/api/v1/namespaces/kubeless/configmaps/kubeless-config failed, reason: connect ECONNREFUSED 127.0.0.1:8080 +3ms
  app:server Error: request to http://localhost:8080/api/v1/namespaces/kubeless/configmaps/kubeless-config failed, reason: connect ECONNREFUSED 127.0.0.1:8080 +21m
  app:server Error: request to http://localhost:8080/api/v1/pods failed, reason: connect ECONNREFUSED 127.0.0.1:8080 +13ms
  app:server Error: request to http://localhost:8080/apis/kubeless.io/v1beta1/functions failed, reason: connect ECONNREFUSED 127.0.0.1:8080 +1ms
  app:server Error: request to http://localhost:8080/api/v1/namespaces/kubeless/configmaps/kubeless-config failed, reason: connect ECONNREFUSED 127.0.0.1:8080 +81ms
  app:server Error: request to http://localhost:8080/api/v1/namespaces/kubeless/configmaps/kubeless-config failed, reason: connect ECONNREFUSED 127.0.0.1:8080 +25m
  app:server Error: request to http://localhost:8080/api/v1/namespaces/kubeless/configmaps/kubeless-config failed, reason: connect ECONNREFUSED 127.0.0.1:8080 +16ms
```
all pod are running
```
# kubectl get pod --all-namespaces
NAMESPACE              NAME                                          READY   STATUS    RESTARTS   AGE
default                hello-f765f6fbd-p4r4c                         1/1     Running   0          5h16m
kube-system            coredns-546565776c-28cw2                      1/1     Running   0          5h25m
kube-system            coredns-546565776c-xd825                      1/1     Running   0          5h25m
kube-system            etcd-pc09                                     1/1     Running   0          5h25m
kube-system            kube-apiserver-pc09                           1/1     Running   0          5h25m
kube-system            kube-controller-manager-pc09                  1/1     Running   0          5h25m
kube-system            kube-proxy-48mml                              1/1     Running   0          5h25m
kube-system            kube-scheduler-pc09                           1/1     Running   0          5h25m
kube-system            storage-provisioner                           1/1     Running   0          5h25m
kubeless               kubeless-controller-manager-59d484f4d-9zpjg   3/3     Running   0          5h19m
kubeless               ui-698c9989-4bhcx                             2/2     Running   0          66m
kubernetes-dashboard   dashboard-metrics-scraper-84bfdf55ff-rlrrv    1/1     Running   0          5h25m
kubernetes-dashboard   kubernetes-dashboard-bc446cc64-hls4t          1/1     Running   0          5h25m
```
and i cannot curl 8080 on server
```
# curl 127.0.0.1:8080
curl: (7) Failed to connect to 127.0.0.1 port 8080: 拒绝连接
# kubectl logs ui-698c9989-4bhcx -n kubeless -c proxy
Starting to serve on 127.0.0.1:8080
```
help!!!!

**Comment by Achonger09** [comment]
```
kubectl get svc -n kubeless
NAME   TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
ui     NodePort   10.111.27.232   <none>        3000:30288/TCP   20m
```
i can create function when i use 30288 as port
